<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Assistant.Infrastructure/Assistant.Infrastructure.csproj" />
  </ItemGroup>

</Project>
