// <auto-generated />
using System;
using Assistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssistantDbContext))]
    [Migration("20261007071324_ImageCallAttempts")]
    partial class ImageCallAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Domain.Bots.Bot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_at");

                    b.Property<long>("LastUpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_update_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TelegramBotId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_bot_id");

                    b.Property<byte[]>("TokenEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("token_encrypted");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_bots");

                    b.HasIndex("TelegramBotId")
                        .IsUnique()
                        .HasDatabaseName("ix_bots_telegram_bot_id");

                    b.ToTable("bots", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Bots.PendingBotCreation", b =>
                {
                    b.Property<long>("CreatorTelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_telegram_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("CreatorTelegramUserId")
                        .HasName("pk_pending_bot_creations");

                    b.ToTable("pending_bot_creations", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Diagnostics.DebugTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AccountedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("accounted_bytes");

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<string>("BuildIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_identity");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("FinalOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("final_outcome");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LastDisposition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_disposition");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<int>("OmittedEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("omitted_event_count");

                    b.Property<long>("PayloadBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("payload_bytes");

                    b.Property<bool>("Redacted")
                        .HasColumnType("boolean")
                        .HasColumnName("redacted");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<long?>("SourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_message_id");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<bool>("Truncated")
                        .HasColumnType("boolean")
                        .HasColumnName("truncated");

                    b.Property<long?>("UpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("update_id");

                    b.HasKey("Id")
                        .HasName("pk_debug_traces");

                    b.HasIndex("SourceMessageId")
                        .HasDatabaseName("ix_debug_traces_source_message_id");

                    b.HasIndex("BotId", "UpdateId")
                        .IsUnique()
                        .HasDatabaseName("ix_debug_traces_bot_id_update_id")
                        .HasFilter("update_id IS NOT NULL");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_debug_traces_created_at_id");

                    b.ToTable("debug_traces", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Diagnostics.DebugTraceCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("EvictedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("evicted_count");

                    b.Property<DateTimeOffset?>("LastEvictedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evicted_at");

                    b.Property<long>("RetainedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("retained_bytes");

                    b.HasKey("Id")
                        .HasName("pk_debug_trace_coverage");

                    b.ToTable("debug_trace_coverage", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Diagnostics.DebugTraceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountedBytes")
                        .HasColumnType("integer")
                        .HasColumnName("accounted_bytes");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<long?>("LlmCallId")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_call_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer")
                        .HasColumnName("payload_bytes");

                    b.Property<long?>("PendingRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("pending_record_id");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<long?>("RelatedSourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_source_message_id");

                    b.Property<long?>("SourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_debug_trace_events");

                    b.HasIndex("LlmCallId")
                        .HasDatabaseName("ix_debug_trace_events_llm_call_id");

                    b.HasIndex("RelatedSourceMessageId")
                        .HasDatabaseName("ix_debug_trace_events_related_source_message_id");

                    b.HasIndex("SourceMessageId")
                        .HasDatabaseName("ix_debug_trace_events_source_message_id");

                    b.HasIndex("TraceId", "Id")
                        .HasDatabaseName("ix_debug_trace_events_trace_id_id");

                    b.ToTable("debug_trace_events", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Families.Family", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Families.FamilyMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("FamilyId", "TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_telegram_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Health.HealthEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.PrimitiveCollection<string[]>("Flags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("flags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OccurredAtSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occurred_at_source");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<long?>("RecordedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<long?>("SourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_message_id");

                    b.Property<string>("SubjectTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_tag");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_events_profile_id");

                    b.HasIndex("SourceMessageId")
                        .HasDatabaseName("ix_events_source_message_id");

                    b.HasIndex("FamilyId", "ProfileId", "Type", "OccurredAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_events_family_id_profile_id_type_occurred_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Health.HealthProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergies");

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<string>("Conditions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("conditions");

                    b.Property<string>("ContextNote")
                        .HasColumnType("text")
                        .HasColumnName("context_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorContacts")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("doctor_contacts");

                    b.Property<string>("DoctorPlan")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("doctor_plan");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("103 или 112")
                        .HasColumnName("emergency_phone");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("Medications")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("medications");

                    b.Property<DateOnly?>("StageStartDate")
                        .HasColumnType("date")
                        .HasColumnName("stage_start_date");

                    b.Property<string>("SubjectTag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("health")
                        .HasColumnName("subject_tag");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_health_profiles");

                    b.HasIndex("BotId")
                        .IsUnique()
                        .HasDatabaseName("ix_health_profiles_bot_id");

                    b.ToTable("health_profiles", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Health.PendingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string[]>("AlertedRuleKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("alerted_rule_keys")
                        .HasDefaultValueSql("'{}'");

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("events");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<int?>("PromptMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_message_id");

                    b.Property<long?>("RequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<long?>("ResolvedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<long?>("SourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_records");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_pending_records_profile_id");

                    b.HasIndex("FamilyId", "SourceMessageId")
                        .HasDatabaseName("ix_pending_records_family_id_source_message_id");

                    b.ToTable("pending_records", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Health.SafetyAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_key");

                    b.Property<decimal?>("Threshold")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("threshold");

                    b.Property<string>("ThresholdSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("threshold_source");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_safety_alerts");

                    b.HasIndex("EventId", "RuleKey")
                        .IsUnique()
                        .HasDatabaseName("ix_safety_alerts_event_id_rule_key");

                    b.ToTable("safety_alerts", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Health.SafetyRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<decimal?>("HighAlert")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("high_alert");

                    b.Property<decimal?>("HighUrgent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("high_urgent");

                    b.Property<decimal?>("LowAlert")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("low_alert");

                    b.Property<decimal?>("LowUrgent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("low_urgent");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SymptomLevel")
                        .HasColumnType("text")
                        .HasColumnName("symptom_level");

                    b.Property<decimal?>("TargetHigh")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("target_high");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int?>("WindowHours")
                        .HasColumnType("integer")
                        .HasColumnName("window_hours");

                    b.HasKey("Id")
                        .HasName("pk_safety_rules");

                    b.HasIndex("ProfileId", "RuleKey")
                        .IsUnique()
                        .HasDatabaseName("ix_safety_rules_profile_id_rule_key");

                    b.ToTable("safety_rules", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.BudgetNotice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PeriodKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_kind");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_budget_notices");

                    b.HasIndex("PeriodKind", "PeriodStart", "Threshold")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_notices_period_kind_period_start_threshold");

                    b.ToTable("budget_notices", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.ChatSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long?>("ContextStartMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("context_start_message_id");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("PreferredModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("preferred_model");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_settings");

                    b.HasIndex("BotId", "ChatId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_settings_bot_id_chat_id_topic_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("BotId", "ChatId", "TopicId"), false);

                    b.ToTable("chat_settings", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.LlmCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AttemptKey")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_key");

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<decimal?>("ReportedCost")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("reported_cost");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<long?>("TriggerMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("trigger_message_id");

                    b.HasKey("Id")
                        .HasName("pk_llm_calls");

                    b.HasIndex("AttemptKey")
                        .IsUnique()
                        .HasDatabaseName("ix_llm_calls_attempt_key")
                        .HasFilter("attempt_key IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_llm_calls_created_at");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_llm_calls_family_id_created_at");

                    b.ToTable("llm_calls", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Messages.ChatMigration", b =>
                {
                    b.Property<long>("FromChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_chat_id");

                    b.Property<DateTimeOffset>("MigratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("migrated_at");

                    b.Property<long>("ToChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_chat_id");

                    b.HasKey("FromChatId")
                        .HasName("pk_chat_migrations");

                    b.ToTable("chat_migrations", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Messages.StoredMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chat_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("In")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<long?>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_messages_family_id");

                    b.HasIndex("BotId", "ChatId", "TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_bot_id_chat_id_telegram_message_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Places.Place", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ReplyToAll")
                        .HasColumnType("boolean")
                        .HasColumnName("reply_to_all");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("BotId", "ChatId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_places_bot_id_chat_id_topic_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("BotId", "ChatId", "TopicId"), false);

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Diagnostics.DebugTrace", b =>
                {
                    b.HasOne("Assistant.Domain.Messages.StoredMessage", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_debug_traces_messages_source_message_id");
                });

            modelBuilder.Entity("Assistant.Domain.Diagnostics.DebugTraceEvent", b =>
                {
                    b.HasOne("Assistant.Domain.Llm.LlmCall", null)
                        .WithMany()
                        .HasForeignKey("LlmCallId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_debug_trace_events_llm_calls_llm_call_id");

                    b.HasOne("Assistant.Domain.Diagnostics.DebugTrace", null)
                        .WithMany()
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_debug_trace_events_debug_traces_trace_id");
                });

            modelBuilder.Entity("Assistant.Domain.Health.HealthEvent", b =>
                {
                    b.HasOne("Assistant.Domain.Health.HealthProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_health_profiles_profile_id");
                });

            modelBuilder.Entity("Assistant.Domain.Health.PendingRecord", b =>
                {
                    b.HasOne("Assistant.Domain.Health.HealthProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pending_records_health_profiles_profile_id");
                });

            modelBuilder.Entity("Assistant.Domain.Health.SafetyAlert", b =>
                {
                    b.HasOne("Assistant.Domain.Health.HealthEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_safety_alerts_events_event_id");
                });

            modelBuilder.Entity("Assistant.Domain.Health.SafetyRule", b =>
                {
                    b.HasOne("Assistant.Domain.Health.HealthProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_safety_rules_health_profiles_profile_id");
                });
#pragma warning restore 612, 618
        }
    }
}
