// <auto-generated />
using System;
using Assistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssistantDbContext))]
    [Migration("20261001003038_M3bBudgets")]
    partial class M3bBudgets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Domain.Bots.Bot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<long>("LastUpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_update_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TelegramBotId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_bot_id");

                    b.Property<byte[]>("TokenEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("token_encrypted");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_bots");

                    b.HasIndex("TelegramBotId")
                        .IsUnique()
                        .HasDatabaseName("ix_bots_telegram_bot_id");

                    b.ToTable("bots", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Bots.PendingBotCreation", b =>
                {
                    b.Property<long>("CreatorTelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_telegram_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("CreatorTelegramUserId")
                        .HasName("pk_pending_bot_creations");

                    b.ToTable("pending_bot_creations", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Families.Family", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Families.FamilyMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("FamilyId", "TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_telegram_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.BudgetNotice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PeriodKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_kind");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_budget_notices");

                    b.HasIndex("PeriodKind", "PeriodStart", "Threshold")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_notices_period_kind_period_start_threshold");

                    b.ToTable("budget_notices", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.ChatSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long?>("ContextStartMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("context_start_message_id");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("PreferredModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("preferred_model");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_settings");

                    b.HasIndex("BotId", "ChatId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_settings_bot_id_chat_id_topic_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("BotId", "ChatId", "TopicId"), false);

                    b.ToTable("chat_settings", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Llm.LlmCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<decimal?>("ReportedCost")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("reported_cost");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_llm_calls");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_llm_calls_family_id_created_at");

                    b.ToTable("llm_calls", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Messages.ChatMigration", b =>
                {
                    b.Property<long>("FromChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_chat_id");

                    b.Property<DateTimeOffset>("MigratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("migrated_at");

                    b.Property<long>("ToChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_chat_id");

                    b.HasKey("FromChatId")
                        .HasName("pk_chat_migrations");

                    b.ToTable("chat_migrations", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Messages.StoredMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chat_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("In")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<long?>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_messages_family_id");

                    b.HasIndex("BotId", "ChatId", "TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_bot_id_chat_id_telegram_message_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Assistant.Domain.Places.Place", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("BotId", "ChatId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_places_bot_id_chat_id_topic_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("BotId", "ChatId", "TopicId"), false);

                    b.ToTable("places", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
